disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Joshua B. Moore"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "profile.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Joshua B. Moore"
  email = "jmoo2880@uni.sydney.edu.au"
  image = "profile.png"
  imageQuality = 96
  headline = "PhD student, [Dynamics and Neural Systems Group](https://dynamicsandneuralsystems.github.io), University of Sydney"
  #bio = "A little bit about you"
  links = [
      { email = "mailto:jmoo2880@uni.sydney.edu.au" },
      { github = "https://github.com/joshuabmoore" },
      { medium = "https://medium.com/jmoo2880" },
      { orcid = "https://orcid.org/0000-0002-5237-1087" },
      { linkedin = "https://linkedin.com/in/joshua-moore-500906221/" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
      ]